### ISSUE TITLE
Submit this package to packagist

### ISSUE THREAD

**Issue by jfoliveira** [careerbuilder/php-oauth#4]
Hi,

It would be nice to be able to install this package as a dependency by running:
```
composer require cbdr/php-oauth
```

Could you submit it to `https://packagist.org/packages/cbdr/php-oauth`?

Thanks!

**Comment by piteur** [comment]
Hi 

If you have a composer.json file just put a "repository" node to include this git repository.
Please find an example here : https://github.com/cbdr/luceo/blob/master/composer.json

Packagist isn't mandatory to include package and it makes sense for private package like this one.

**Comment by jfoliveira** [comment]
Hey @piteur thanks for replying! The link you mentioned is broken.

I managed to get it working by reading composer documentation, so here are the meaningful parts of my `composer.json` for reference in case others come here with the same issue:

```json
    "require": {
        "careerbuilder/php-oauth": "*"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "careerbuilder/php-oauth",
                "version": "0.1.0",
                "type": "package",
                "source": {
                    "url": "https://github.com/careerbuilder/php-oauth.git",
                    "type": "git",
                    "reference": "master"
                }
            }
        }
    ],
```
