### ISSUE TITLE
Autoload not working

### ISSUE THREAD

**Issue by jfoliveira** [careerbuilder/php-oauth#5]
Hi, just installed this package and tried to add the classes to my `use` clause as the example displayed on the `READ.ME`:

```php
use CareerBuilder\OAuth2\OAuth2Plugin;
use CareerBuilder\OAuth2\TokenFactory;
use CareerBuilder\OAuth2\NullTokenStorage;
use CareerBuilder\OAuth2\Flows\ClientCredentials;
...
```
This causes the fatal error `Class not found`.

Tried requiring the file `bootstrap.php` as shown in [usage.php](https://github.com/careerbuilder/php-oauth/blob/master/usage.php) but this also doesn't work as the bootstrap 
```php
require_once('vendor/autoload.php');
```
is trying to load a local `vendor` folder inside the package directory and not on the app root dir.

Do I have to perform any further steps in order to be able to load this package's classes?

**Comment by sakai135** [comment]
Please know that the `usage.php` is provided as an example, and you may have to adjust some values. Take a look at the [documentation about autoloading for Composer](https://getcomposer.org/doc/01-basic-usage.md#autoloading).

**Comment by jfoliveira** [comment]
Thanks for replying!
Even after running `composer dump-autoload` this package's data is not added to `vendor/composer/autoload*.php` files. I don't know if this is due to the fact you're using `PSR-0` (all other packages I use with composer adopted `PSR-4` standard).

Does `composer dump-autoload` works for you generating  the namespace in `vendor/composer/autoload_namespaces.php`?
```php
return array(
    'phpDocumentor' => array($vendorDir . '/phpdocumentor/reflection-docblock/src'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'CareerBuilder' => ... // should be generated here?
...
```

**Comment by jfoliveira** [comment]
Fixed by adding/duplicating `autoload` node to the `repositories` property:

```javascript
    "require": {
        "careerbuilder/php-oauth": "*"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "careerbuilder/php-oauth",
                "version": "0.1.0",
                "type": "package",
                "source": {
                    "url": "https://github.com/careerbuilder/php-oauth.git",
                    "type": "git",
                    "reference": "master"
                },
                "autoload": { /* required when using `repositories` although not clearly documented by composer team */
                   "psr-0": {
                   "CareerBuilder\\": "src/"
              }
        }
    }
            }
        }
    ],
```
