### ISSUE TITLE
How to map CB credentials to config object?

### ISSUE THREAD

**Issue by jfoliveira** [careerbuilder/php-oauth#6]
Hi, I've just receive my credentials from the APIAuth team and they look like this:
```json
{
  "client_data": {
    "id": "...",
    "owner_id": "...",
    "app_name": "...",
    "app_description": "...",
    "signature": "..."
  }
```

The config object displayed on the `README` example has the following properties:
```php
$configs = array(
    'client_id' => '', // this is fine, I will just use the client_data.id
    'client_secret' => '', // what to pass here?
    'shared_secret' => '', // what is the shared secret?
    'base_url' => 'https://www.careerbuilder.com'
);
```

Could you tell me which fields from credentials should be used in each config object's parameter?

Thanks!

**Comment by sakai135** [comment]
`client_secret` can be a string of your choosing. `shared_secret` should have been provided to you.

**Comment by jfoliveira** [comment]
I contacted the APIAuth team and they say the `signature` should be used as the `shared_secret`.
Thanks!
